version: "3.6"
services:
  myjdownloader:
    container_name: myjdownloader
    image: jaymoulin/jdownloader:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../data/myjdownloader/config:/opt/JDownloader/cfg
      - ../data/myjdownloader/logs:/opt/JDownloader/logs
      - ${MYJD_DOWNLOAD_VOLUME}:/opt/JDownloader/Downloads
    environment:
      - MYJD_USER=${MYJD_USER}
      - MYJD_PASSWORD=${MYJD_PASSWORD}
      - MYJD_DEVICE_NAME=${MYJD_DEVICE_NAME}
      - XDG_DOWNLOAD_DIR=/opt/JDownloader/Downloads
      - LANG=es_ES.UTF-8
      - LANGUAGE=es_ES:es
    ports:
      - ${MYJD_EXPOSE_PORT}:3129
    restart: always
    
  tautulli:
    container_name: tautulli
    image: tautulli/tautulli:latest
    volumes:
      - ../data/tautulli/config:/config
      - ${TAUTULLI_PLEX_DIRECTORY}/Logs:/plex_logs
    environment:
      - PUID=${PLEX_USER_ID}
      - PGID=${PLEX_GROUP_ID}
      - TZ=${TAUTULLI_TIMEZONE}
    ports:
      - ${TAUTULLI_EXPOSE_PORT}:8181
