version: "3.6"
services:
  api_ddd:
    container_name: api_ddd
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    image: ${IMAGE_API_NAME}:1.0
    depends_on:
      - ddd_database
      - myjdownloader
    volumes:
      - ../app:/usr/src/app:ro
      - ${DOWNLOAD_VOLUME}:/downloads
      - ${MOVIES_VOLUME_FULLHD}:/movies_fullhd
      - ${MOVIES_VOLUME_4K}:/movies_4k
    environment:
      - PYTHONUNBUFFERED=1
    command: python app.py
    restart: always

  ddd_database:
    container_name: ddd_database
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=${DB_TIMEZONE}
    ports:
      - "${DB_EXPOSE_PORT}:3306"
    volumes:
      - ../container_data/ddd_database/mysql:/var/lib/mysql
      - ../data/sql/dbmovies.sql:/docker-entrypoint-initdb.d/${DB_DATABASE}.sql:ro
    healthcheck:
      test: ["CMD", "mysqlshow", "${DB_DATABASE}", "--user=${DB_USER}", "--password=${DB_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  myjdownloader:
    container_name: myjdownloader
    image: jaymoulin/jdownloader:latest
    user: ${PLEX_USER_ID}:${PLEX_GROUP_ID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../container_data/myjdownloader/config:/opt/JDownloader/cfg
      - ../container_data/myjdownloader/logs:/opt/JDownloader/logs
      - ${DOWNLOAD_VOLUME}:/opt/JDownloader/Downloads
    environment:
      - MYJD_USER=${MYJD_USER}
      - MYJD_PASSWORD=${MYJD_PASSWORD}
      - MYJD_DEVICE_NAME=${MYJD_DEVICE_NAME}
      - XDG_DOWNLOAD_DIR=/opt/JDownloader/Downloads
      - LANG=es_ES.UTF-8
      - LANGUAGE=es_ES:es
    ports:
      - ${MYJD_EXPOSE_PORT}:3129
    restart: always
    
  tautulli:
    container_name: tautulli
    image: tautulli/tautulli:latest
    volumes:
      - ${PLEX_DIRECTORY}/TautulliConfig:/config
      - ${PLEX_DIRECTORY}/Logs:/plex_logs
    environment:
      - PUID=${PLEX_USER_ID}
      - PGID=${PLEX_GROUP_ID}
      - TZ=${TAUTULLI_TIMEZONE}
    ports:
      - ${TAUTULLI_EXPOSE_PORT}:8181
