version: "3.6"
services:
  api_ddd:
    container_name: api_ddd
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    image: ${IMAGE_API_NAME}:1.0
    depends_on:
      - ddd_database
    volumes:
      - ../app:/usr/src/app:ro
      - ${API_DOWNLOAD_VOLUME}:/downloads
      - ${API_MOVIES_VOLUME_FULLHD}:/movies_fullhd
      - ${API_MOVIES_VOLUME_4K}:/movies_4k
    environment:
      - PYTHONUNBUFFERED=1
    command: python app.py
    restart: always

  ddd_database:
    container_name: ddd_database
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=dbmovies
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=${DB_TIMEZONE}
    ports:
      - "${DB_EXPOSE_PORT}:3306"
    volumes:
      - ../data/ddd_database/mysql:/var/lib/mysql
      - ../config/sql/dbmovies.sql:/docker-entrypoint-initdb.d/dbmovies.sql:ro
    healthcheck:
      test: ["CMD", "mysqlshow", "dbmovies", "--user=${DB_USER}", "--password=${DB_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
